### PR TITLE
[#a8q1ux] Adding dashboard notebooks

### PR DESCRIPTION
**Pull request by jsignell**
The only notebook that really matters is the dashboard.ipynb but the others generate aggregated data and do some exploratory analysis. If we decide to keep them all then I'll add some text to the notebooks to make it easier to follow.

### CODE REVIEW

**Comment by jsignell** [comment]
image
image
image

**Comment by jsignell** [comment]
There is some room for more elements in ML.

**Comment by rikturr** [comment]
Can the data files be in S3 instead? I added an `TAXI_S3` env variable with my last PR, it would be good to write there inside `data/dashboard` so that way we don't have data files in git

**Comment by jameslamb** [comment]
are you looking for a review on this? Or is it still in progress?

**Comment by jsignell** [comment]
Ok. This is done.

image
image
image

**Pull request merged**
